insert into materia values (-1,'Todas');
insert into materia values (7502,'Administración de Proyectos de Software');
insert into materia values (7500,'Administración y Gestión de Proyectos de Software');
insert into materia values (5523,'Algoritmos y complejidad');
insert into materia values (7508,'Análisis de Lenguajes de Programación');
insert into materia values (5534,'Análisis y diseño de sistemas');
insert into materia values (5561,'Arquitectura de computadoras');
insert into materia values (7526,'Arquitectura de Computadoras para Ingeniería');
insert into materia values (7525,'Arquitectura y organización de computadoras');
insert into materia values (5559,'Arquitecturas modernas');
insert into materia values (7534,'Auditoría de Sistemas');
insert into materia values (7535,'Auditoría de sistemas y legislación');
insert into materia values (7552,'Bases de Datos');
insert into materia values (5576,'Compiladores e Intérpretes');
insert into materia values (5583,'Computación Gráfica');
insert into materia values (7615,'Conceptos de Inteligencia Artificial');
insert into materia values (7629,'Datamining y aprendizaje automatizado');
insert into materia values (7631,'Desarrollo ágil de software');
insert into materia values (7633,'Desarrollo de Aplicaciones Orientado a Objetos');
insert into materia values (7641,'Didáctica de la computación');
insert into materia values (5587,'Diseño y desarrollo de software');
insert into materia values (7642,'Elementos de Bases de Datos');
insert into materia values (7645,'Elementos de Programación');
insert into materia values (5616,'Estructuras de archivos');
insert into materia values (7655,'Estructuras de Datos');
insert into materia values (5617,'Estructuras de datos y algoritmos');
insert into materia values (5611,'Estructuras de Programación');
insert into materia values (7660,'Evolución de la informática');
insert into materia values (5633,'Fundamentos de Ciencias de la Computación');
insert into materia values (7661,'Fundamentos de la Web Semántica');
insert into materia values (5678,'Informática A');
insert into materia values (7681,'Ingeniería de Aplicaciones para la Web Semántica');
insert into materia values (7680,'Ingeniería de Aplicaciones Web');
insert into materia values (5684,'Inteligencia Artificial');
insert into materia values (0,'Inteligencia Artificial para Juegos');
insert into materia values (7703,'Interacción Humano Computadora');
insert into materia values (5692,'Introducción a la Informática');
insert into materia values (7714,'Introducción a la Ingeniería de Software');
insert into materia values (7710,'Introducción a la Operación de Computadoras Personales');
insert into materia values (7713,'Introducción a la Programación Orientada a Objetos');
insert into materia values (7718,'Introducción a las estructuras de datos');
insert into materia values (5696,'Lenguajes de Programación');
insert into materia values (7790,'Lenguajes formales');
insert into materia values (7791,'Lenguajes Formales y Autómatas');
insert into materia values (5704,'Lógica para Ciencias de la Computación');
insert into materia values (7595,'M. de Computación Científica');
insert into materia values (7810,'Métodos de Computación Científica');
insert into materia values (5758,'Métodos numéricos A');
insert into materia values (9999,'Minería de la Web');
insert into materia values (7821,'Modelos de Software');
insert into materia values (5744,'Organización de computadoras');
insert into materia values (7897,'Paralelismo y concurrencia en sistemas');
insert into materia values (7887,'Principios y herramientas de programación');
insert into materia values (5746,'Programación orientada a objetos');
insert into materia values (7903,'Redes de Computadoras');
insert into materia values (5786,'Redes y teleprocesamiento');
insert into materia values (5793,'Resolución de problemas y algoritmos');
insert into materia values (7900,'Robótica cognitiva');
insert into materia values (7901,'Seguridad en Sistemas');
insert into materia values (5946,'Simulación');
insert into materia values (5941,'Sistemas distribuídos');
insert into materia values (7919,'Sistemas Embebidos');
insert into materia values (7921,'Sistemas multiagentes y aplicaciones');
insert into materia values (5949,'Sistemas operativos');
insert into materia values (7925,'Sistemas Operativos y Distribuidos');
insert into materia values (7930,'Taller de Operacion de Computadoras');
insert into materia values (7951,'Tecnología de Programación');
insert into materia values (5951,'Tecnología informática en la educación');
insert into materia values (7948,'Tecnologías en Educación Matemática');
insert into materia values (9998,'Tecnologías Para la Programación de Servidores');
insert into materia values (7949,'Teoria de la Computabilidad');
insert into materia values (5954,'Teoría y Diseño de Bases de Datos');
insert into materia values (5979,'Tesis de Licenciatura');
insert into materia values (1202,'Optativa');
insert into materia values (1203,'Optativa');
insert into materia values (1204,'Optativa');
insert into materia values (1205,'Optativa');
insert into materia values (35,'Optativa');
insert into materia values (36,'Optativa');

insert into materia values (7895,'Proyecto Final');
insert into materia values (7820,'Modelos Estadísticos para Cs. de la Computación');

insert into materia values (3051,'Física I');
insert into materia values (2907,'Técnicas Digitales');
insert into materia values (3052,'Física II');
insert into materia values (2516,'Análisis de Circuitos Eléctricos');
insert into materia values (5654,'Funciones de Variable Compleja');
insert into materia values (2761,'Introducción a la Electrónica');
insert into materia values (5551,'Análisis Matemático I');
insert into materia values (5552,'Análisis Matemático II');
insert into materia values (5912,'Elementos de Algebra y Geometría');

insert into tipo_examen (nombreTipoExamen,Materia_id)values ('Examen oral',-1);
insert into tipo_examen (nombreTipoExamen,Materia_id)values ('Examen escrito',-1);
insert into tipo_examen (nombreTipoExamen,Materia_id)values ('Coloquio',-1);
insert into tipo_examen (nombreTipoExamen,Materia_id)values ('Promoción',-1);

